# Generated by Django 4.2.11 on 2024-03-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_is_favorite_alter_advertisement_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='is_favorite',
            new_name='user_favorites',
        ),
    ]
